#!/bin/bash
# Script 5: Open Source Manifesto Generator
# Author: Aarat Sahajpal | Course: Open Source Software

echo "=========================================="
echo "   Open Source Manifesto Generator"
echo "=========================================="
echo ""
 
# --- User Input ---
read -p "1. Name one open-source tool you use every day: " TOOL
read -p "2. In one word, what does 'freedom' mean to you? " FREEDOM
read -p "3. Name one thing you would build and share freely: " BUILD

DATE=$(date '+%d %B %Y')
OUTPUT="manifesto_$(whoami).txt"

# --- Generate Manifesto ---
echo "------------------------------------------" > $OUTPUT
echo "Open Source Manifesto" >> $OUTPUT
echo "Date: $DATE" >> $OUTPUT
echo "" >> $OUTPUT

echo "I believe in the power of open source. Tools like $TOOL show how collaboration can create powerful software accessible to everyone." >> $OUTPUT
echo "To me, freedom means $FREEDOM — the ability to use, modify, and share software without restrictions." >> $OUTPUT
echo "In the future, I would love to build $BUILD and share it openly with the world to contribute to the community." >> $OUTPUT
echo "" >> $OUTPUT
echo "— Generated by $(whoami)" >> $OUTPUT
echo "------------------------------------------" >> $OUTPUT

# --- Output ---
echo ""
echo "Manifesto saved to $OUTPUT"
echo ""
cat $OUTPUT
